test2:
  
  hardware_interface:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - f_joint1
      - f_joint2
    sim_control_mode: 1  # 0: position, 1: velocity
  
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    - name: gripper_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - f_joint1
        - f_joint2
  gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - f_joint1
      - f_joint2
    gains:
      f_joint1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      f_joint2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    gains:
      joint1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

  # gripper_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint1
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # arm_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint2
  #   pid: {p: 100.0, i: 0.01, d: 10.0}



